
project_id = "lxiqvvourradjjhocxrd"

[api]
enabled = true
port = 54323
schemas = ["public", "storage", "auth"]

[db]
port = 54322

[studio]
port = 54324

# Edge Functions
[functions.check-course-access]
verify_jwt = false
