
project_id = "lxiqvvourradjjhocxrd"

[api]
enabled = false

[db]
enabled = false

[realtime]
enabled = false

[storage]
enabled = false

[edge_functions]
enabled = true

[[edge_functions.function]]
name = "check-course-access"
verify_jwt = false
