
project_id = "lxiqvvourradjjhocxrd"

[api]
enabled = true
port = 54323
schemas = ["public", "storage", "auth"]

[db]
port = 54322

[studio]
port = 54324

[functions.check-course-access]
verify_jwt = false

[functions.course-plan]
verify_jwt = false

[functions.project-knowledge]
verify_jwt = false

[functions.save-memory]
verify_jwt = false

[functions.get-memories]
verify_jwt = false
