// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxiqvvourradjjhocxrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4aXF2dm91cnJhZGpqaG9jeHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjMwMjEsImV4cCI6MjA2MDU5OTAyMX0.-pk6ZtNudMtA0KkhM7IFJVE9UYjD9ldq_Ci6YiO9uqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);